apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-queue-config
  namespace: webhook-queue
data:
  API_PORT: "3000"
  WORKER_METRICS_PORT: "3001"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  QUEUE_NAME: "webhook-delivery"
  APP_VERSION: "k8s"
  JOB_ATTEMPTS: "3"
  JOB_BACKOFF_MS: "2000"
  WORKER_CONCURRENCY: "2"
  LOG_LEVEL: "info"